// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvggdwcxdseiixzufqri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12Z2dkd2N4ZHNlaWl4enVmcXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTk4OTgsImV4cCI6MjA2OTg5NTg5OH0.Jc9Cs7YTxY0y9ZXd1CqJZS3UC2XVLNJe81bTlUC0ULU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});